zoomLimits parameter for KML
geops/react-spatial pull request #652
Opened 2021-02-24 15:24 UTC by danji90

# How to

A _zoomLimits_ parameter has been added to the KML read/write methods. It writes a stringified array into the kml and parses it into the feature properties when reading.

# Others

- [ ] It's not a hack or at least an unauthorized hack :).
- [ ] The images added are optimized.
- [ ] Everything in ticket description has been fixed.
- [ ] The author of the MR has made its own review before assigning the reviewer.
- [ ] IE11 tested.
- [ ] The title means something for a human being.
- [ ] The title contains [WIP] if it's necessary.
- [ ] Labels applied. if it's a release? a hotfix?
- [ ] Tests added.

2021-02-25 15:15 UTC, oterral commented on src/utils/KML.js
> +    // In case a fill pattern should be applied (use fillPattern attribute to store pattern id, color etc)
Is this comment reöltaed to zoomLimits?

2021-02-25 16:46 UTC, danji90 commented
@oterral I fixed the comment

2021-05-17 11:42 UTC, oterral commented on src/utils/KML.js
> +    feature.set('minZoom', parseInt(feature.get('minZoom'), 10));
I would use parseFloat maybe we will want to use 8.5 some day

2021-05-17 11:43 UTC, oterral requested changes
Use parseFloat instead of parseInt

2021-05-17 13:00 UTC, merged